"""HeadHunter provider — returns mock candidates (real API requires registered app credentials)."""
from .base import ExternalCandidate

_MOCK_CANDIDATES: list[dict] = [
    {
        "full_name": "Аманов Ержан Болатович",
        "position": "Nuclear Safety Engineer",
        "skills": ["IAEA standards", "Risk assessment", "PSA", "Radiation protection", "VVER"],
        "past_projects": ["Akkuyu NPP Turkey", "Rooppur NPP Bangladesh"],
        "experience_years": 9,
        "employer": "Росатом",
        "location": "Алматы",
        "salary": "от 800 000 KZT",
        "telegram": "@amanov_nuclear",
    },
    {
        "full_name": "Козлов Андрей Сергеевич",
        "position": "Lead Welding Inspector",
        "skills": ["ASME IX", "NDE certification", "QA/QC", "TIG", "MIG", "Field inspection"],
        "past_projects": ["Kursk NPP-2 Russia", "Temirtau Steel Plant"],
        "experience_years": 12,
        "employer": "АтомМонтаж",
        "location": "Нур-Султан",
        "salary": "от 700 000 KZT",
        "telegram": "@kozlov_weld",
    },
    {
        "full_name": "Бекмуратова Айгуль",
        "position": "Construction Project Coordinator",
        "skills": ["Project management", "Scheduling", "Primavera P6", "Russian language", "AutoCAD"],
        "past_projects": ["Astana LRT Project", "Tengiz Oil Expansion"],
        "experience_years": 7,
        "employer": "KazStroyInvest",
        "location": "Алматы",
        "salary": "от 600 000 KZT",
        "telegram": "@bekmurat_pm",
    },
    {
        "full_name": "Сулейменов Дархан",
        "position": "Radiation Protection Specialist",
        "skills": ["Dosimetry", "ALARA principles", "Regulatory compliance", "NRC standards"],
        "past_projects": ["VVER-1200 Certification Russia", "Ulba Metallurgical Plant"],
        "experience_years": 11,
        "employer": "КазАтомПром",
        "location": "Усть-Каменогорск",
        "salary": "от 750 000 KZT",
        "telegram": "@suleim_rad",
    },
    {
        "full_name": "Ким Виктор Алексеевич",
        "position": "Electrical Systems Technician",
        "skills": ["Industrial wiring", "PLC programming", "Safety systems", "SCADA", "High voltage"],
        "past_projects": ["Almaty Power Station", "Balkhash CHP"],
        "experience_years": 5,
        "employer": "ЭнергоСервис KZ",
        "location": "Алматы",
        "salary": "от 500 000 KZT",
        "telegram": "@kim_electric",
    },
    {
        "full_name": "Мухамедов Рустам",
        "position": "Civil Engineer — Nuclear Structures",
        "skills": ["Reinforced concrete", "Seismic design", "ASME III", "Nuclear construction"],
        "past_projects": ["Barakah NPP UAE", "Rooppur NPP Bangladesh"],
        "experience_years": 14,
        "employer": "Samsung C&T",
        "location": "Алматы",
        "salary": "от 1 200 000 KZT",
        "telegram": "@mukhamedov_civil",
    },
    {
        "full_name": "Петрова Наталья Ивановна",
        "position": "QA/QC Inspector",
        "skills": ["ISO 9001", "Quality control", "NDT", "Documentation", "Nuclear grade"],
        "past_projects": ["Leningrad NPP-2 Russia", "Metsamor NPP Armenia"],
        "experience_years": 8,
        "employer": "АтомЭксперт",
        "location": "Нур-Султан",
        "salary": "от 650 000 KZT",
        "telegram": "@petrova_qa",
    },
    {
        "full_name": "Нурланов Бекзат",
        "position": "I&C Engineer (Instrumentation & Control)",
        "skills": ["DCS", "FPGA", "Nuclear I&C", "IEC 61513", "Reactor control systems"],
        "past_projects": ["Tianwan NPP China", "VVER-1000 upgrade"],
        "experience_years": 10,
        "employer": "Schneider Electric KZ",
        "location": "Алматы",
        "salary": "от 900 000 KZT",
        "telegram": "@nurlanov_ic",
    },
]


class HHProvider:
    async def search(self, keywords: list[str], limit: int = 10) -> list[ExternalCandidate]:
        return [ExternalCandidate(**c, source_id=f"hh-mock-{i}") for i, c in enumerate(_MOCK_CANDIDATES[:limit])]
